// <auto-generated />
namespace RegistroJATICS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pendingchanges2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pendingchanges2));
        
        string IMigrationMetadata.Id
        {
            get { return "201702110759419_pendingchanges2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
